### PR TITLE
Simple Theme Integration

### PR DESCRIPTION
**Pull request by s-saens**
# Theme Integration

I love this package and its nice looking, but I felt a bit uncomfortable as I use dark mode while this package uses only constant light colors. Moreover, I cannot set a builder parameter for the dropdown field. So I simply applied theme color values.

I think many user would use theme system so if this pull request is published, many of them may not need some complicated builders to customize it.

I've committed a modification of `main.dart` file too, and it is unnecessary for the production but I recommend you to merge it too.

_**Ready for production**_

---
Light Mode
Dark Mode

### CODE REVIEW

**Comment by ParsaZa79** [comment]
I hope this request to get merged sooner.
It could solve my issue as well.

**Comment by AbdullahChauhan** [comment]
Hey @s-saens Thanks for the contribution.
Hi to you guys @ParsaZa79 @karniv00l 
Got some time to go through this. What I am thinking instead of directly integrate application theme into the package code. It would be great to provide the API `theme: CustomDropdownThemeData(...)` having all the possible theme related properties. This way developer can either provider their theme props or provide the other values if not using the app theme.

**Comment by ParsaZa79** [comment]
This would be even more satisfying. Waiting to see the update dear @AbdullahChauhan!

**Comment by s-saens** [comment]
That would be nice :)

**Pull request closed without merging**
