### PR TITLE
Multi select controller

### LINKED ISSUE #57: Need Clear button
how to add clear button

### PR DESCRIPTION
**Pull request by hbatalhaStch**
This PR allows you to use a controller to select/clear multi-select dropdown items programmatically.

closes #57

### CODE REVIEW

**Comment by ParsaZa79** [comment]
Please merge this pull request 🙏

**Comment by AbdullahChauhan** [comment]
Hey @hbatalhaStch Thank you for your contribution, appreciated.
I'm start reviewing this. Will merge soon if all good!

CC: @ParsaZa79

**Comment by hbatalhaStch** [comment]
@AbdullahChauhan you could also include a single select controller. see [this](https://github.com/hbatalhaStch/custom-dropdown/blob/ec8a6ab93939085c138f14d586abee448c177ca0/lib/models/controller.dart#L21)

**Comment by AbdullahChauhan** [comment]
> @AbdullahChauhan you could also include a single select controller. see [this](https://github.com/hbatalhaStch/custom-dropdown/blob/ec8a6ab93939085c138f14d586abee448c177ca0/lib/models/controller.dart#L21)

Hey, Yes. Already started this in a separate branch. Thanks for the reference!

**Pull request merged**
