### PR TITLE
Preview: Migrate package to generic type. Work with List<T> instead of List<String>

### PR DESCRIPTION
**Pull request by JesusHdez960717**
### This PR is a preview, not ready for production yet.

This PR includes migrating the package to work with `List<T>` instead of `List<String>`.
This enhancement makes it easier to handle more complex objects.
The migration of the 'core' of the package is complete (with superficial tests), styling details remain, error handling, some extreme cases and documentation according to the modifications.
To simplify and organize the work, the TODO list is left below:
  - [X] Migration of the operating logic of the package to work with `List<T>`.
  - [X] Generation of usage examples (in main.dart, also main2.dart for a fully customized example).
  - [x] Package style for further customization. (I can't think of any more customizations)
  - [x] Error handling.
  - [x] Documentation.
  - [x] Testing
  - [x] Visual example in README

### CODE REVIEW

**Comment by JesusHdez960717** [comment]
Conflicts are in the identation of the asserts, nothing to worry about for the moment.

**Comment by AbdullahChauhan** [comment]
Hey @JesusHdez960717 Yeah, no worries about the conflicts for now. Really appreciate your work. Btw I must say, this is really fast work :raised_hands:

**Comment by jarvesusaram99** [comment]
Hey, please merge the code, i am using custom dropdown, but i want validator for each dropdown. Please merge ASAP.

**Comment by JesusHdez960717** [comment]
Hi @jarvesusaram99, I am very happy to know that you are interested in the changes that are being made, unfortunately they are more of a technical preview at the moment, it still needs some improvements and a lot of tests, especially since the entire project has been refactored.
So at the moment I don't think the changes will be merged.
In any case, if you want to use or test what has been done, you can try the following:
1 - Fork the repo
2 - Do the changes needed, maybe merged the branch `generic_type_migration` into master (test it first).
3 - In the project dependencies instead of working with:

`animated_cutom_dropdown: ^version you are using`

use:
```dart
animated_cutom_dropdown:
  path: your path to your forked github repo
```
you can use `ref:` property if you want to point to something other than master

**Comment by JesusHdez960717** [comment]
@AbdullahChauhan I belive the changes are ready for a first review on your side.
I included in the main.dart the update in the use of the package, with what I thought are most of the use cases covered. 
Very excited with the progress so far. :satisfied:. I hope you like what has been done.
I would like your feedback to make the modifications accordingly.

**Comment by JesusHdez960717** [comment]
@AbdullahChauhan it's a pleasure to help.
From my part, at least for now, it's over, feel free to change everything you need.
I hope when you review it you liked the work.
I look forward to your review.

**Comment by JesusHdez960717** [comment]
@AbdullahChauhan any updates?

**Comment by AbdullahChauhan** [comment]
> @AbdullahChauhan any updates?

Hey @JesusHdez960717 Actually, I've been very busy these days so couldn't get enough time to review this. Whenever I get free time, I'll try my best to review and merge this. Thanks!

**Comment by JesusHdez960717** [comment]
BTW @AbdullahChauhan, i'm using this PR in two production Android app, and it's working perfect.

**Comment by KabaDH** [comment]
@AbdullahChauhan hello and thank you for this amazing package! I would greatly appreciate it if this pr could be merged, so I could add a multiselect option.

https://github.com/AbdullahChauhan/custom-dropdown/assets/96592168/fc29cf57-cdef-4fb1-b5a9-09f486861cf1

**Comment by AbdullahChauhan** [comment]
Hey @JesusHdez960717, @KabaDH 
Already start reviewing this. Will merge soon :blush:

**Pull request merged**
